-- AlterTable: User writing defaults + branding
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultGenre" TEXT NOT NULL DEFAULT 'Fiction';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultTone" TEXT NOT NULL DEFAULT 'Professional';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultAudience" TEXT NOT NULL DEFAULT 'General readers';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultTargetPages" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultPov" TEXT NOT NULL DEFAULT 'third';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultTense" TEXT NOT NULL DEFAULT 'past';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultLanguage" TEXT NOT NULL DEFAULT 'en';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultModel" TEXT NOT NULL DEFAULT 'gpt-4o-mini';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultCreativity" DOUBLE PRECISION NOT NULL DEFAULT 0.7;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultWordsPerPage" INTEGER NOT NULL DEFAULT 300;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultSectionsPerChapter" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "styleGuide" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "autoGenerateOnCreate" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailNotifications" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "brandName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "brandTagline" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "authorName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "imprintName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "brandColor" TEXT NOT NULL DEFAULT '#635bff';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "copyrightNotice" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dedicationDefault" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "exportFooter" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "includeBrandInExport" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable: Book advanced generation settings
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "pov" TEXT NOT NULL DEFAULT 'third';
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "tense" TEXT NOT NULL DEFAULT 'past';
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'en';
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "chapterCount" INTEGER;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "sectionsPerChapter" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "wordsPerPage" INTEGER NOT NULL DEFAULT 300;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "includeDialogue" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "includeExamples" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "customInstructions" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "characters" JSONB;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "themes" JSONB;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "forbiddenTopics" TEXT;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "model" TEXT NOT NULL DEFAULT 'gpt-4o-mini';
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "creativity" DOUBLE PRECISION NOT NULL DEFAULT 0.7;
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "templateId" TEXT;
